### ISSUE TITLE
AADSTS70001, Application is not supported for this API version

### ISSUE THREAD

**Issue by imyoungyang** [jasonjoh/o365-tutorial#11]
Hi,

I followed your steps but I registered the app at  [azure portal](https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps)

After I clicked login, I got the following error message:

{"error"=>"unauthorized_client",
 "error_description"=>
  "AADSTS70001: Application '2e432bd2-dacc-45a7-841e-8ca5f13213f9' is not supported for this API version.\r\n" +
  "Trace ID: dc5ea262-8455-46a1-96d7-f32d979a0700\r\n" +
  "Correlation ID: 77cf8900-3355-499f-8e98-a6903996be5d\r\n" +
  "Timestamp: 2017-04-20 09:42:44Z"}

Please tell us how we can fix this error message.

The following is our setting screenshots.
[![https://gyazo.com/b31bfbcbfec8f3ad2d6b664beabcd8de](https://i.gyazo.com/b31bfbcbfec8f3ad2d6b664beabcd8de.png)](https://gyazo.com/b31bfbcbfec8f3ad2d6b664beabcd8de)

[![https://gyazo.com/9501178378222aea8949b3b17083afa7](https://i.gyazo.com/9501178378222aea8949b3b17083afa7.png)](https://gyazo.com/9501178378222aea8949b3b17083afa7)

**Comment by imyoungyang** [comment]
@jasonjoh 

Could you help me on this?

Thanks.

**Comment by jasonjoh** [comment]
Question: why did you choose the Azure portal over apps.dev.microsoft.com? That's why you're seeing the error here. I'm not saying it's a "wrong" choice, but I'm trying to understand if there was some specific reason.

In any event, the "Application '2e432bd2-dacc-45a7-841e-8ca5f13213f9' is not supported for this API version" message means that you're app is trying to authorize using the Azure V2 endpoint, but you've registered in the Azure portal, which only supports the v1 endpoints. You'll need to modify the sample to use v1 if you want it to work with your current app registration. The version of this sample in the v1 branch should give you an idea of what you need to do.

Of course, an easier fix would be to register it in the apps.dev.microsoft.com portal and use that app ID :).

**Comment by imyoungyang** [comment]
Hi Jason

Because we are using o365 for my company domain not outlook.com domain, I have to set up in the Azure AD for my company domain.

I found why these errors happened, there are two steps need to do:
1. I have to use specific endpoints under App registration > endpoints menu. 

[![https://gyazo.com/9938fba7ffbf1cc1acfa5f33a49368a5](https://i.gyazo.com/9938fba7ffbf1cc1acfa5f33a49368a5.png)](https://gyazo.com/9938fba7ffbf1cc1acfa5f33a49368a5)

2. Must click on "grant permissions" on the menu bar although the application does not use any administrators' required services.

[![https://gyazo.com/ac0e52377ac35f9d8c364fb3d4b57146](https://i.gyazo.com/ac0e52377ac35f9d8c364fb3d4b57146.png)](https://gyazo.com/ac0e52377ac35f9d8c364fb3d4b57146)

After doing so, I can use o365 to login and get token.

Thank you for your reponses.

**Comment by jasonjoh** [comment]
No problem. I will point out that you can still use apps.dev.microsoft.com with your corporate account to register in your AD :). However, sounds like you're good to go from here.

**Comment by imyoungyang** [comment]
thanks for your reply.
